language: java
jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=15
  - IDEA_VERSION=16

install: ./gradlew extractIdeaSdk

script: ./gradlew test dist
sudo: false
cache:
  directories:
  - $HOME/.gradle
  - lib
